import React, { Fragment, useEffect } from 'react';
import '../../../assets/css/Footer/Terms.scss';
import Nav from '../../include/Nav';
import { Link } from 'react-router-dom';
import Resbtn from '../../include/Resbtn';

const Terms = () =>  {
    useEffect(() => {
        const body = document.querySelector('#root');
        body.scrollIntoView({
            behavior: 'smooth'
        }, 500)
      }, []);
        return (
            <Fragment>
                <div className="terms_section_1">
                    <div className="container">
                        <div id="nav_box1" style={{display: "flex", justifyContent: "flex-end", alignItems: "center", position: "relative"}}>
                            <Link to="/"><img className="img-fluid" src="assets/img/index/logo.png" width="200" height="30" alt="" style={{ position: "absolute", top: "20%", left: "0" }} /></Link>
                            <Nav />
                        </div>
                        <div id="nav_box2" style={{display: "none", justifyContent: "flex-end", alignItems: "center", position: "relative"}}>
                            <Link to="/"><img className="img-fluid" src="assets/img/index/logo.png" width="200" height="30" alt="" style={{ position: "absolute", top: "40%", left: "0" }} /></Link>
                            {/* <Link to="" className="nav-link navbar_rightbox" href="#" >
                            &nbsp;&nbsp;<img className="img-fluid" src="assets/img/index/Iconawesome-user-alt.png" width="19.05" height="19.05" alt="" />&nbsp;&nbsp;Account
                                
                            </Link> */}
                            <Resbtn />
                        </div>
                    </div>
                </div>
                <div className="terms_section_2">
                    <div className="container">
                        <p className="terms_title">Ox Stocks – Terms of Use</p>
                        <div className="panel1">
                            <p className="terms_title">1. Introduction</p>
                            <p className="terms_subtitle">These Terms of Use (“Terms”) govern your use of and access to www.oxstocks.com (“Website”), owned and operated by Ox Stocks Pty Ltd ACN 654 485 300 (“Ox Stocks” “we,” “us” or “our”). These Terms govern your access to and use of the Website; including without limitation the creation, purchase, sale, exchange, or modification of certain digital assets and physical goods; our online and/or other services, and software provided on or in connection with those services (collectively, the “Service”).</p>
                            <p className="terms_subtitle">This Service also allows you to sell and purchase both physical goods requiring physical shipping and delivery (“Physical Goods”) and/or acquire Crypto Assets (as defined below) via auction (“Auction”) or the Website marketplace (“Marketplace”). Detailed rules regarding the Auction and Marketplace process are available on the Website. You may only participate in the Auction by using your Ox Coin holdings or other Crypto Asset listed on Ox Stocks only.</p>
                            <p className="terms_subtitle">“Crypto Assets” refers to Ox Coin, non-fungible tokens or “NFTs” using smart contracts, or any other digital asset at our sole discretion.</p>
                            <p className="terms_subtitle">“Assets” refers to both Crypto Assets, Ox Coin and Physical Goods sold at Auction or on the Ox Stocks Marketplace.</p>
                            <p className="terms_subtitle">“Physical Goods” refers to tangible goods, products or other items sold on the Ox Stocks Marketplace.</p>
                            <p className="terms_subtitle">ALL TRANSACTIONS INITIATED THROUGH OUR SERVICE ARE FACILITATED AND RUN BY THIRD-PARTY ELECTRONIC WALLET EXTENSIONS, AND BY USING OUR SERVICES YOU AGREE THAT YOU ARE GOVERNED BY THE TERMS OF SERVICE AND PRIVACY POLICY FOR THE APPLICABLE EXTENSIONS.</p>
                            <p className="terms_subtitle">OX STOCKS IS A PLATFORM. WE ARE NOT A BROKER, FINANCIAL INSTITUTION, OR CREDITOR. WE DO NOT PROVIDE FINANCIAL ADVICE. AS SUCH, WE DO NOT HOLD AN AUSTRALIAN FINANCIAL SERVICES LICENSE. THE SERVICES ARE AN ADMINISTRATIVE PLATFORM ONLY. OX STOCKS FACILITATES TRANSACTIONS BETWEEN THE BUYER AND SELLER IN A MARKETPLACE OR AUCTION BUT IS NOT A PARTY TO ANY AGREEMENT BETWEEN THE BUYER AND SELLER OF CRYPTO ASSETS OR PHYSICAL GOODS OR BETWEEN ANY USERS.</p>
                            <p className="terms_subtitle">YOU BEAR FULL RESPONSIBILITY FOR VERIFYING THE IDENTITY, LEGITIMACY, AND AUTHENTICITY OF ASSETS YOU PURCHASE ON OX STOCKS. NOTWITHSTANDING INDICATORS AND MESSAGES THAT SUGGEST VERIFICATION, OX STOCKS MAKES NO CLAIMS ABOUT THE IDENTITY, LEGITIMACY, OR AUTHENTICITY OF ASSETS ON THE PLATFORM.</p>
                            <p className="terms_subtitle">Because we have a growing number of services, we sometimes need to describe additional terms for specific services. Those additional terms and conditions, which are available with the relevant services, then become part of your agreement with us if you use those services.</p>
                            <p className="terms_subtitle">THESE TERMS OF USE ARE IMPORTANT AND AFFECT YOUR LEGAL RIGHTS, SO PLEASE READ THEM CAREFULLY. WE WANT TO LET YOU KNOW THAT THE TERMS INCLUDE AN ARBITRATION AGREEMENT WHICH WILL, WITH LIMITED EXCEPTIONS, REQUIRE DISPUTES BETWEEN US TO BE SUBMITTED TO BINDING AND FINAL ARBITRATION. UNLESS YOU OPT OUT OF THE ARBITRATION AGREEMENT: (1) YOU WILL ONLY BE PERMITTED TO PURSUE CLAIMS AND SEEK RELIEF AGAINST US ON AN INDIVIDUAL BASIS, NOT AS A PLAINTIFF OR CLASS MEMBER IN ANY CLASS OR REPRESENTATIVE ACTION OR PROCEEDING; AND (2) YOU ARE AGREEING TO MANDATORY INDIVIDUAL ARBITRATION FOR THE RESOLUTION OF DISPUTES AND WAIVING YOUR RIGHT TO A JURY TRIAL ON YOUR CLAIMS. PLEASE READ SECTION 15 CAREFULLY.</p>
                            <p className="terms_subtitle">BY CLICKING ON THE “I ACCEPT” BUTTON, COMPLETING THE ACCOUNT REGISTRATION PROCESS, USING OUR SERVICES AND/OR PURCHASING CRYPTO ASSETS, YOU AGREE TO BE BOUND BY THESE TERMS AND ALL OF THE TERMS INCORPORATED HEREIN BY REFERENCE. If you do not agree to these Terms, you may not access or use the Service or purchase the Assets.</p>
                            <p className="terms_subtitle">Ox Stocks reserves the right to change or modify these Terms at any time and in our sole discretion. If we make changes to these Terms, we will provide notice of such changes, such as by sending an email notification, providing notice through the Service or updating the “Last Updated” date at the beginning of these Terms. By continuing to access or use the Service, you confirm your acceptance of the revised Terms and all of the terms incorporated therein by reference. We encourage you to review the Terms frequently to ensure that you understand the terms and conditions that apply when you access or use the Service. If you do not agree to the revised Terms, you may not access or use the Service.</p>
                        </div>
                        <div className="panel2">
                            <p className="terms_title">2. Privacy Policy</p>
                            <p className="terms_subtitle">Please refer to our Privacy Policy for information about how we collect, use and share personal information about you.</p>
                        </div>
                        <div className="panel3">
                            <p className="terms_title">3. Account Registration and Communication Preferences</p>
                            <p className="terms_subtitle">a. If you wish to participate in an Auction for Assets, you will need to register for an account on the Service (“Account”). By creating an Account, you agree to (a) provide accurate, current and complete Account information about yourself, (b) maintain and promptly update from time to time as necessary your Account information, (c) maintain the security of your password and accept all risks of unauthorized access to your Account and the information you provide to us, and (d) immediately notify us if you discover or otherwise suspect any security breaches related to the Service, or your Account. Ox Stocks will block multiple accounts of the same user. Also, you agree that you will not:</p>
                            <p className="terms_subtitle">- create another account if we’ve disabled one you had unless you have our written permission first;</p>
                            <p className="terms_subtitle">- buy, sell, rent or lease access to your Account or username unless you have our written permission first;</p>
                            <p className="terms_subtitle">- share your Account password with anyone; or</p>
                            <p className="terms_subtitle">- log in or try to log in to access the Service through unauthorized third party applications or clients.</p>
                            <p className="terms_subtitle">b. Ox Stocks may require you to provide additional information and documents at the request of any competent authority or in case of application of any applicable law or regulation, including laws related to anti-laundering (legalisation) of incomes obtained by criminal means, or for counteracting financing of terrorism. Ox Stocks may also require you to provide additional information and documents in cases where it has reasons to believe that:</p>
                            <p className="terms_subtitle">- Your Account is being used for money laundering or for any other illegal activity;</p>
                            <p className="terms_subtitle">- You have concealed or reported false identification information and other details; or</p>
                            <p className="terms_subtitle">- Transactions effected via your Account were effected in breach of these Terms.</p>
                            <p className="terms_subtitle">In such cases, Ox Stocks, in its sole discretion, may pause or cancel your Auction transactions until such additional information and documents are reviewed by Ox Stocks and accepted as satisfying the requirements of applicable law. If you do not provide complete and accurate information and documents in response to such a request, Ox Stocks may refuse to provide the Content (defined in Section 4(A) below) to you.</p>
                            <p className="terms_subtitle">c. By creating an Account, you consent to receive electronic communications from Ox Stocks (e.g., via email or by posting notices to the Service). These communications may include notices about your Account (e.g., password changes and other transactional information) and are part of your relationship with us. You agree that any notices, agreements, disclosures or other communications that we send to you electronically will satisfy any legal communication requirements, including, but not limited to, that such communications be in writing. You should maintain copies of electronic communications from us by printing a paper copy or saving an electronic copy. We may also send you promotional communications via email, including, but not limited to, newsletters, special offers, surveys and other news and information we think will be of interest to you. You may opt out of receiving these promotional emails at any time by following the unsubscribe instructions provided therein.</p>
                            <p className="terms_subtitle">d. By submitting personal data through our Site or Services, you agree to the terms of our Privacy Policy and you expressly consent to the collection, use and disclosure of your personal data in accordance with the Privacy Policy.</p>
                            <p className="terms_subtitle">e. You must provide all equipment and software necessary to connect to the Service and services, including but not limited to, a mobile device that is suitable to connect with and use Service and services, in cases where the Service offers a mobile component. You are solely responsible for any fees, including Internet connection or mobile fees, that you incur when accessing the Service or services.</p>
                            <p className="terms_subtitle">f. Notwithstanding anything to the contrary in these Terms, the Service and Content may include software components provided by Ox Stocks or its affiliates or a third party that are subject to separate license terms, in which case those license terms will govern such software components. For example, when you click to get more details about any of the Assets sold through our marketplace, you will notice a third party link to the website from which such Crypto Asset originated. Such website may include license terms governing the use of such Crypto Asset. In the event you purchase such Crypto Asset through our marketplace, you are required to comply with such terms.</p>
                            <p className="terms_subtitle">g. As stated above, your participation in the Auction is also subject to the Auction and Marketplace Rules available on the Website.</p>
                        </div>
                        <div className="panel4">
                            <p className="terms_title">4. Ownership</p>
                            <p className="terms_subtitle">a. Unless otherwise indicated in writing by us, the Service and all content and other materials contained therein, including, without limitation, the Ox Stocks logo and all designs, text, graphics, pictures, information, data, software, sound files, other files and the selection and arrangement thereof (collectively, “Content”) are the proprietary property of Ox Stocks or our affiliates, licensors or users, as applicable.</p>
                            <p className="terms_subtitle">b. Notwithstanding anything to the contrary in these Terms, the Service and Content may include software components provided by Ox Stocks or its affiliates or a third party that are subject to separate license terms, in which case those license terms will govern such software components.</p>
                            <p className="terms_subtitle">c. The Ox Stocks logo and any Ox Stocks product or service names, logos or slogans that may appear on the Service or Service are trademarks of Ox Stocks or our affiliates and may not be copied, imitated or used, in whole or in part, without our prior written permission. You may not use any metatags or other “hidden text” utilizing “Ox Stocks” or any other name, trademark or product or service name of Ox Stocks or our affiliates without our prior written permission. In addition, the look and feel of the Service and Content, including, without limitation, all page headers, custom graphics, button icons and scripts, constitute the service mark, trademark or trade dress of Ox Stocks and may not be copied, imitated or used, in whole or in part, without our prior written permission. All other trademarks, registered trademarks, product names and Ox Stocks names or logos mentioned on the Service are the property of their respective owners and may not be copied, imitated or used, in whole or in part, without the permission of the applicable trademark holder. Reference to any products, services, processes or other information by name, trademark, manufacturer, supplier or otherwise does not constitute or imply endorsement, sponsorship or recommendation by Ox Stocks.</p>
                        </div>
                        <div className="panel5">
                            <p className="terms_title">5. License to Access and Use Our Service and Content</p>
                            <p className="terms_subtitle">You are hereby granted a limited, nonexclusive, nontransferable, nonsublicensable, and personal license to access and use the Service and Content; provided, however, that such license is subject to these Terms and does not include any right to (a) sell, resell or use commercially the Service or Content, (b) distribute, publicly perform or publicly display any Content, (c) modify or otherwise make any derivative uses of the Service or Content, or any portion thereof, (d) use any data mining, robots or similar data gathering or extraction methods, (e) download (other than page caching) any portion of the Service or Content, except as expressly permitted by us, and (f) use the Service or Content other than for their intended purposes.</p>
                        </div>
                        <div className="panel6">
                            <p className="terms_title">6. Hyperlinks</p>
                            <p className="terms_subtitle">You are granted a limited, nonexclusive, nontransferable right to create a text hyperlink to the Service for noncommercial purposes, provided that such link does not portray Ox Stocks or our affiliates or any of our products or services in a false, misleading, derogatory or otherwise defamatory manner, and provided further that the linking site does not contain any adult or illegal material or any material that is offensive, harassing or otherwise objectionable. This limited right may be revoked at any time. You may not use a logo or other proprietary graphic of Ox Stocks to link to the Service or Content without our express written permission. Further, you may not use, frame or utilize framing techniques to enclose any Ox Stocks trademark, logo or other proprietary information, including the images found on the Service, the content of any text or the layout or design of any page, or form contained on a page, on the Service without our express written consent.</p>
                        </div>
                        <div className="panel7">
                            <p className="terms_title">7. Third Party Services</p>
                            <p className="terms_subtitle">The Service may contain links to third-party websites (“Third-Party Websites”) and applications (“Third-Party Applications”). When you click on a link to a Third-Party Website or Third-Party Application, we will not warn you that you have left our Service and are subject to the Terms and conditions (including privacy policies) of another website or destination. Such Third-Party Websites and Third-Party Applications and are not under the control of Ox Stocks. Ox Stocks is not responsible for any Third-Party Websites or Third-Party Applications. Ox Stocks provides these Third-Party Websites and Third-Party Applications only as a convenience and does not review, approve, monitor, endorse, warrant, or make any representations with respect to Third-Party Websites or Third-Party Applications, or their products or services. You use all links in Third-Party Websites, and Third-Party Applications at your own risk. When you leave our Service, our Terms and policies no longer govern. You should review all applicable agreements and policies, including privacy and data gathering practices, of any Third-Party Websites or Third-Party Applications, and should make whatever investigation you feel necessary or appropriate before proceeding with any transaction with any third party.</p>
                        </div>
                        <div className="panel8">
                            <p className="terms_title">8. User Conduct</p>
                            <p className="terms_subtitle">You agree that you will not violate any law, contract, intellectual property or other third party right, and that you are solely responsible for your conduct, while accessing or using the Service or participating in the Auction. You agree that you will abide by these Terms and will not:</p>
                            <p className="terms_subtitle">a. Provide false or misleading information to Ox Stocks;
b. Use or attempt to use another user’s Account without authorization from such user and Ox Stocks;
c. Create or list counterfeit items;
d. Pose as another person or create a misleading username;
e. Use the Service in any manner that could interfere with, disrupt, negatively affect or inhibit other users from fully enjoying the Service, or that could damage, disable, overburden or impair the functioning of the Service in any manner;
f. Develop, utilize, or disseminate any software, or interact with any API in any manner, that could damage, harm, or impair the Service;
g. Reverse engineer any aspect of the Service, or do anything that might discover source code or bypass or circumvent measures employed to prevent or limit access to any Service, area or code of the Service;
h. Attempt to circumvent any content-filtering techniques we employ, or attempt to access any feature or area of the Service that you are not authorized to access;
i. Use any robot, spider, crawler, scraper, script, browser extension, offline reader or other automated means or interface not authorized by us to access the Service, extract data or otherwise interfere with or modify the rendering of Service pages or functionality;
j. Use data collected from our Service to contact individuals, companies, or other persons or entities;
k. Use data collected from our Service for any direct marketing activity (including without limitation, email marketing, SMS marketing, telemarketing, and direct marketing);
l. Bypass or ignore instructions that control all automated access to the Service;
m. Use the Service for any illegal or unauthorized purpose, or engage in, encourage or promote any activity that violates these Terms;
n. Use Ox Stocks to carry out any illegal activities, including but not limited to money laundering, terrorist financing or deliberately engaging in activities designed to adversely affect the performance of Ox Stocks, or the Service;
o. Engage in wash trading or other deceptive or manipulative trading activities;
p. Place misleading bids or offers;
q. Spam listings for the purpose of causing a listing to appear at the top of the search results;
r. Engage in behaviors that have the intention or the effect of artificially increasing view counts, favorites, volume, or other metrics that Ox Stocks might use to sort search results;
s. Use the Service to carry out any financial activities subject to registration or licensing, including but not limited to creating, listing, or buying securities, commodities, options, real estate, or debt instruments;
t. Use the Service from a country sanctioned by the government of the United States; or
u. Use the Service to participate in fundraising for a business, protocol, or platform, including but not limited to creating, listing, or buying assets that are redeemable for financial instruments, assets that give owners rights to participate in an initial coin offering or any securities offering, or assets that entitle owners to financial rewards, including but not limited to, DeFi yield bonuses, staking bonuses, and burn discounts.</p>
                            <p className="terms_subtitle">Ox Stocks facilitates trade among a diverse community of buyers and sellers. Openness is one of our most prized values, and we're committed to providing a platform for the exchange of a wide range of content, including controversial or novel (but, in our reasonable opinion, not derogatory, vulgar, inhumane or explicit) content. These policies ensure that our marketplace offers the widest selection of assets possible while promoting trust and respect, as well as adherence to the law.</p>
                            <p className="terms_subtitle">Ox Stocks has always exercised judgment in allowing or disallowing certain assets, listings, smart contracts, and collections consistent with the spirit of openness in a worldwide community of users of a radical new technology. We carefully consider the complete situation and all its details in light of our policies before deciding to remove inappropriate assets, listings, smart contracts, and collections when we discover them or they're brought to our attention.</p>
                            <p className="terms_subtitle">Assets, listings, smart contracts, and collections that Ox Stocks deems inappropriate, disruptive, or illegal are prohibited on Ox Stocks. Ox Stocks reserves the rights to determine the appropriateness of listings on its site and remove any listing at any time. If you create or offer an asset, listing, smart contract, or collection in violation of these policies, we will take corrective actions, as appropriate, including but not limited to removing the asset, listing, smart contract, or collection, deleting your Ox Stocks account, and permanently withholding referral payments and developer revenue sharing fees. Ox Stocks cannot destroy or impound your assets or smart contracts, but we reserve the right to destroy inappropriate metadata stored on our servers.</p>
                            <p className="terms_subtitle">Assets, listings, smart contracts, and collections that include metadata that violates international or United States intellectual property laws, promotes suicide or self-harm, incites hate or violence against others, degrades or doxes another individual, depicts minors in sexually suggestive situations, or is otherwise illegal in the United States are prohibited on Ox Stocks and will be removed.</p>
                            <p className="terms_subtitle">Assets, listings, smart contracts, and collections with a primary or substantial purpose in a game or application that violates international or United States intellectual property laws, promotes suicide or self-harm, incites hate or violence against others, degrades or doxes another individual, depicts minors in sexually suggestive situations, or is otherwise illegal in the United States are prohibited on Ox Stocks and will be removed.</p>
                            <p className="terms_subtitle">Assets, listings, smart contracts, and collections created or used primarily or substantially for the purpose of raising funds for the known terrorist organizations listed on https://www.nationalsecurity.gov.au/Listedterroristorganisations/Pages/default.aspx are prohibited on Ox Stocks and will be removed.</p>
                            <p className="terms_subtitle">The sale of stolen assets, converted assets, fraudulently obtained assets, assets taken without authorization, and other illegally obtained assets on Ox Stocks is prohibited. Listing illegally obtained assets may result in your listings being cancelled, your assets being hidden, or your account being suspended.</p>
                            <p className="terms_subtitle">If you have reason to believe that an asset listed on Ox Stocks was illegally obtained, please contact us immediately at legal@oxstocks.com. Include the asset's ID, the asset's contract address, and evidence demonstrating that the asset was illegally obtained. Ox Stocks will review your claim and reply within 72 hours. If we determine from the evidence that the asset is stolen, we will hide it or disable trading of it.</p>
                            <p className="terms_subtitle">We require all users to be 18 years old or older. If you are under 18, you may use a parent or guardian's Ox Stocks account, but only with involvement of the account holder. However, the account holder is responsible for everything done with that account.</p>
                            <p className="terms_subtitle">Not safe for work (“NSFW”) content is meant for people who are 18 years and older. We allow the Asset sales of this content, but it is subject to being marked NSFW and handled differently than non-NSFW content in navigation menus and search results. Asset names, listings and their descriptions, smart contract names, and collections including profanity or overtly sexual content are prohibited on Ox Stocks and will be removed. A smart contract that contains NSFW content is subject to being marked NSFW, even if the NSFW content only represent a portion of the content on the smart contract.</p>
                            <p className="terms_subtitle">Ox Stocks does not permit the listing of illegal or offensive content, such as products that depict graphic sexual acts and images that depict children under the age of 18 in a sexually suggestive manner on the Website.</p>
                            <p className="terms_subtitle">Ox Stocks reserves the right to remove any listing or Content which, in its sole discretion, it considers to be in breach of these Terms or otherwise promotes violence (in any form) or denigrates any group, class, gender, sex, creed or race of people.</p>
                            <p className="terms_subtitle">If you become aware of the creation, listing, or buying of Assets in violation of any of the terms specified in this section, you agree to contact us to report it. Creators bear special responsibility for informing Ox Stocks of the existence of their collections, contracts, and assets that violate these Terms.</p>
                        </div>
                        <div className="panel9">
                            <p className="terms_title">9. User Information and Copyright</p>
                            <p className="terms_subtitle">You are solely responsible for your use of the Services and for any User Information you provide, including compliance with applicable laws, rules, and regulations. We take no responsibility for the User Information posted or listed via the Services. You retain your rights to any User Information you submit, post, or display using the Services.</p>
                            <p className="terms_subtitle">By submitting, posting or displaying User Information on or through the Services, you grant us a worldwide, non-exclusive, sublicensable, royalty-free license to use, copy, modify, and display any text, content, files, communications, comments, feedback, suggestions, ideas, concepts, questions, data or other content that you submit or post on or through the Services or through tools or applications we provide for posting or sharing such content (collectively “User Information”) for our lawful business purposes, including to provide, promote, and improve the Services.</p>
                            <p className="terms_subtitle">You represent and warrant that you have, or have obtained, all rights, licenses, consents, permissions, power and/or authority necessary to grant the rights granted herein for any User Information that you submit, post or display on or through the Services. You agree that such User Information will not contain material subject to copyright or other proprietary rights, unless you have necessary permission or are otherwise legally entitled to post the material and to grant Ox Stocks the license described above.</p>
                            <p className="terms_subtitle">Ox Stocks reserves the right to remove Content which infringes these Terms without prior notice. Where appropriate, Ox Stocks reserves the right to remove works in response to valid and formal infringement claims and to terminate a user's access to the Services if the user is determined to be a repeat infringer.</p>
                            <p className="terms_subtitle">If you believe that your content has been copied in a way that constitutes copyright infringement, or your likeness has been used in a way that violates your personality rights, please contact legal@oxstocks.com.</p>
                            <p className="terms_subtitle">Formal infringement claims regarding content on the Services must include: v. A written communication delivered to the email designated above;
w. A physical or electronic signature of someone authorized to act on behalf of the copyright owner;
x. Identification of the copyrighted work(s) allegedly infringed;
y. Identification of material claimed to be infringing, reasonably sufficient to permit Company to locate the material;
z. Information reasonably sufficient to permit Company to contact the complaining party. This can be an address, phone number, email address, or other suitable method of contact;
aa. A statement that the “complaining party has a good faith belief that use of the material in the manner complained of is not authorized by the copyright owner, its agent or the law; and”
bb. A statement that the information in the notice is accurate and, under penalty of perjury, that the complaining party is authorized to act on behalf of the copyright owner.</p>
                        </div>
                        <div className="panel10">
                            <p className="terms_title">10. Indemnification</p>
                            <p className="terms_subtitle">To the fullest extent permitted by applicable law, you agree to indemnify, defend and hold harmless Ox Stocks, and our respective past, present and future employees, officers, directors, contractors, consultants, equity holders, suppliers, vendors, service providers, parent companies, subsidiaries, affiliates, agents, representatives, predecessors, successors and assigns (individually and collectively, the “Ox Stocks Parties”), from and against all actual or alleged third party claims, damages, awards, judgments, losses, liabilities, obligations, penalties, interest, fees, expenses (including, without limitation, attorneys’ fees and expenses) and costs (including, without limitation, court costs, costs of settlement and costs of pursuing indemnification and insurance), of every kind and nature whatsoever, whether known or unknown, foreseen or unforeseen, matured or unmatured, or suspected or unsuspected, in law or equity, whether in tort, contract or otherwise (collectively, “Claims”), including, but not limited to, damages to property or personal injury, that are caused by, arise out of or are related to (a) your use or misuse of the Service, User Information or Assets, (b) any feedback you provide, (c) your violation of these Terms, and (d) your violation of the rights of a third party, including another user or MetaMask. You agree to promptly notify Ox Stocks of any third party Claims and cooperate with the Ox Stocks Parties in defending such Claims. You further agree that the Ox Stocks Parties shall have control of the defense or settlement of any third party Claims. THIS INDEMNITY IS IN ADDITION TO, AND NOT IN LIEU OF, ANY OTHER INDEMNITIES SET FORTH IN A WRITTEN AGREEMENT BETWEEN YOU AND OX STOCKS.</p>
                        </div>
                        <div className="panel11">
                            <p className="terms_title">11. Disclaimers</p>
                            <p className="terms_subtitle">EXCEPT AS EXPRESSLY PROVIDED TO THE CONTRARY IN A WRITING BY OX STOCKS, THE SERVICE, CONTENT CONTAINED THEREIN, AND ASSETS LISTED THEREIN ARE PROVIDED ON AN “AS IS” AND “AS AVAILABLE” BASIS WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, EITHER EXPRESS OR IMPLIED. OX STOCKS (AND ITS SUPPLIERS) MAKE NO WARRANTY THAT THE SERVICE: (A) WILL MEET YOUR REQUIREMENTS; (B) WILL BE AVAILABLE ON AN UNINTERRUPTED, TIMELY, SECURE, OR ERROR-FREE BASIS; OR (C) WILL BE ACCURATE, RELIABLE, COMPLETE, LEGAL, OR SAFE. OX STOCKS DISCLAIMS ALL OTHER WARRANTIES OR CONDITIONS, EXPRESS OR IMPLIED, INCLUDING, WITHOUT LIMITATION, IMPLIED WARRANTIES OR CONDITIONS OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT AS TO THE SERVICE, CONTENT CONTAINED THEREIN. OX STOCKS DOES NOT REPRESENT OR WARRANT THAT CONTENT ON THE SERVICE IS ACCURATE, COMPLETE, RELIABLE, CURRENT OR ERROR-FREE. WE WILL NOT BE LIABLE FOR ANY LOSS OF ANY KIND FROM ANY ACTION TAKEN OR TAKEN IN RELIANCE ON MATERIAL OR INFORMATION, CONTAINED ON THE SERVICE. WHILE OX STOCKS ATTEMPTS TO MAKE YOUR ACCESS TO AND USE OF THE SERVICE AND CONTENT SAFE, OX STOCKS CANNOT AND DOES NOT REPRESENT OR WARRANT THAT THE SERVICE, CONTENT, ANY ASSETS LISTED ON OUR SERVICE OR OUR SERVERS ARE FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS. WE CANNOT GUARANTEE THE SECURITY OF ANY DATA THAT YOU DISCLOSE ONLINE. YOU ACCEPT THE INHERENT SECURITY RISKS OF PROVIDING INFORMATION AND DEALING ONLINE OVER THE INTERNET AND WILL NOT HOLD US RESPONSIBLE FOR ANY BREACH OF SECURITY UNLESS IT IS DUE TO OUR GROSS NEGLIGENCE.</p>
                            <p className="terms_subtitle">WE WILL NOT BE RESPONSIBLE OR LIABLE TO YOU FOR ANY LOSS AND TAKE NO RESPONSIBILITY FOR, AND WILL NOT BE LIABLE TO YOU FOR, ANY USE OF ASSETS, INCLUDING BUT NOT LIMITED TO ANY LOSSES, DAMAGES OR CLAIMS ARISING FROM: (A) USER ERROR SUCH AS FORGOTTEN PASSWORDS, INCORRECTLY CONSTRUCTED TRANSACTIONS, OR MISTYPED ADDRESSES; (B) SERVER FAILURE OR DATA LOSS; (C) CORRUPTED WALLET FILES; (D) UNAUTHORIZED ACCESS TO APPLICATIONS; (E) ANY UNAUTHORIZED THIRD PARTY ACTIVITIES, INCLUDING WITHOUT LIMITATION THE USE OF VIRUSES, PHISHING, BRUTEFORCING OR OTHER MEANS OF ATTACK AGAINST THE SERVICE OR ASSETS.</p>
                            <p className="terms_subtitle">UNLIKE PHYSICAL GOODS, CRYPTO ASSETS ARE INTANGIBLE DIGITAL ASSETS. THEY EXIST ONLY BY VIRTUE OF THE OWNERSHIP RECORD MAINTAINED IN THE BLOCKCHAIN SMART CONTRACT. ANY TRANSFER OF TITLE THAT MIGHT OCCUR IN ANY UNIQUE DIGITAL ASSET OCCURS ON THE DECENTRALIZED LEDGER.</p>
                        </div>
                        <div className="panel12">
                            <p className="terms_title">12. Assumption of Risk</p>
                            <p className="terms_title">A. Crypto Assets</p>
                            <p className="terms_subtitle">You accept and acknowledge: a. The prices of blockchain assets are extremely volatile. Fluctuations in the price of other digital assets could materially and adversely affect the Crypto Assets, which may also be subject to significant price volatility. We cannot guarantee that any purchasers of Crypto Assets will not lose money.
b. You are solely responsible for determining what, if any, taxes apply to your Crypto Assets transactions. Neither Ox Stocks nor any other Ox Stocks Party is responsible for determining the taxes that apply to Crypto Assets transactions.
c. Our Service does not store, send, or receive Crypto Assets. This is because Crypto Assets exist only by virtue of the ownership record maintained on its supporting blockchain. Any transfer of Crypto Assets occurs within the supporting blockchain and not on this Service.
d. There are risks associated with using an Internet based currency, including but not limited to, the risk of hardware, software and Internet connections, the risk of malicious software introduction, and the risk that third parties may obtain unauthorized access to information stored within your wallet. You accept and acknowledge that Ox Stocks will not be responsible for any communication failures, disruptions, errors, distortions or delays you may experience when using the Crypto Assets, however caused.
e. A lack of use or public interest in the creation and development of distributed ecosystems could negatively impact the development of those ecosystems and related applications and could therefore also negatively impact the potential utility or value of Crypto Assets.
f. The regulatory regime governing blockchain technologies, cryptocurrencies, and tokens is uncertain, and new regulations or policies may materially adversely affect the development of the Auction and/or Service and the utility of Crypto Assets.
g. The Service will rely on third-party platforms to perform the transactions for the Auction of Crypto Assets. If we are unable to maintain a good relationship with such platform providers; if the terms and conditions or pricing of such platform providers change; if we violate or cannot comply with the terms and conditions of such platforms; or if any of such platforms loses market share or falls out of favour or is unavailable for a prolonged period, access to and use of the Service will suffer.
h. There are risks associated with purchasing user generated content, including but not limited to, the risk of purchasing counterfeit assets, mislabelled assets, assets that are vulnerable to metadata decay, assets on smart contracts with bugs, and assets that may become untransferable. Ox Stocks reserves the right to hide collections, contracts, and assets affected by any of these issues or by other issues. Assets you purchase may become inaccessible on Ox Stocks. Under no circumstances shall the inability to view your assets on Ox Stocks serve as grounds for a claim against Ox Stocks.</p>
                            <p className="terms_title">B. Physical Goods</p>
                            <p className="terms_subtitle">You accept and acknowledge: a. While we strive to maintain a safe trading environment you accept that there are unfortunately sometimes risks when trading online and using our sites, including dealing with underage or fraudulent persons.
b. You will not hold Ox Stocks responsible for other users' content, actions or inactions, items they list or their destruction of allegedly fake items on our Marketplace or via Auction. You acknowledge that we are not an auctioneer. Instead, Ox Stocks facilitates the ability for users to offer, sell, and buy Crypto Assets and Physical Goods in fixed price and auction-style formats.
a. We are not a party to the sales transaction between buyers and sellers. We have no control over and do not guarantee the quality, safety or legality of items advertised, the truth or accuracy of users' content or listings, the ability of sellers to sell items, the ability of buyers to pay for items or that a buyer or seller will actually complete a transaction or return an item. You should consider and use all reasonable safe trading best practices when trading online.
b. You assume all risk with regard to the quality, safety and/or appropriateness of the Physical Goods.
c. You alone, and not Ox Stocks, are responsible for ensuring that your listing, bidding and selling and any other activities conducted on our site are lawful. You must ensure that you comply with all applicable laws in Australia and other countries. You must also ensure that you strictly comply with this Agreement and the policies which form part of the Agreement.
d. We do not take ownership of the items at any time and do not transfer legal ownership of items from the seller to the buyer. Further, we cannot guarantee continuous or secure access to the Ox Stocks services, and their operation may be interfered with by numerous factors outside of our control. Accordingly, to the extent legally permitted, we exclude all implied warranties, terms and conditions. We are not liable for any loss of money, goodwill or reputation, or any special, indirect or consequential damages arising, directly or indirectly, out of your use of or your inability to use the Ox Stocks services.
e. The prices of Physical Goods will be set by sellers either within the Marketplace or set by demand and supply principles in Auction in accordance with the Auction and Marketplace Rules.
i. Ox Stocks provides the payment platform, Marketplace and Auction facility by which Physical Goods can be bought and sold. It assumes no responsibility and makes no warranty of any kind, express or implied, as to the fitness for purpose or merchantability of any Physical Goods listed on the Website.</p>
                        </div>
                        <div className="panel13">
                            <p className="terms_title">13. Limitation of Liability</p>
                            <p className="terms_subtitle">TO THE FULLEST EXTENT PERMITTED BY LAW, IN NO EVENT WILL OX STOCKS BE LIABLE TO YOU OR ANY THIRD PARTY FOR ANY LOST PROFIT OR ANY INDIRECT, CONSEQUENTIAL, EXEMPLARY, INCIDENTAL, SPECIAL OR PUNITIVE DAMAGES ARISING FROM THESE TERMS, THE SERVICE, PRODUCTS OR THIRD PARTY SITES AND PRODUCTS, OR FOR ANY DAMAGES RELATED TO LOSS OF REVENUE, LOSS OF PROFITS, LOSS OF BUSINESS OR ANTICIPATED SAVINGS, LOSS OF USE, LOSS OF GOODWILL, OR LOSS OF DATA, AND WHETHER CAUSED BY TORT (INCLUDING NEGLIGENCE), BREACH OF CONTRACT, OR OTHERWISE, EVEN IF FORESEEABLE AND EVEN IF OX STOCKS HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. ACCESS TO, AND USE OF, THE SERVICES, PRODUCTS OR THIRD PARTY SITES AND PRODUCTS ARE AT YOUR OWN DISCRETION AND RISK, AND YOU WILL BE SOLELY RESPONSIBLE FOR ANY DAMAGE TO YOUR COMPUTER SYSTEM OR MOBILE DEVICE OR LOSS OF DATA RESULTING THEREFROM.</p>
                            <p className="terms_subtitle">NOTWITHSTANDING ANYTHING TO THE CONTRARY CONTAINED HEREIN, IN NO EVENT SHALL THE MAXIMUM AGGREGATE LIABILITY OF OX STOCKS ARISING OUT OF OR IN ANY WAY RELATED TO THESE TERMS, THE ACCESS TO AND USE OF THE SERVICE, CONTENT, CRYPTO ASSETS, OR ANY PRODUCTS OR SERVICES PURCHASED ON THE SERVICE EXCEED THE GREATER OF (A) $100 OR (B) THE AMOUNT RECEIVED BY OX STOCKS FROM THE SALE OF CRYPTO ASSETS THAT ARE THE SUBJECT OF THE CLAIM.</p>
                            <p className="terms_subtitle">THE FOREGOING LIMITATIONS OF LIABILITY SHALL NOT APPLY TO LIABILITY OF OX STOCKS FOR (A) DEATH OR PERSONAL INJURY CAUSED BY A MEMBER OF OX STOCKS’S NEGLIGENCE; OR FOR (B) ANY INJURY CAUSED BY A MEMBER OF OX STOCKS’S FRAUD OR FRAUDULENT MISREPRESENTATION.</p>
                            <p className="terms_subtitle">Some jurisdictions do not allow the exclusion or limitation of incidental or consequential damages, so the above limitation or exclusion may not apply to you. Some jurisdictions also limit disclaimers or limitations of liability for personal injury from consumer products, so this limitation may not apply to personal injury claims.</p>
                        </div>
                        <div className="panel14">
                            <p className="terms_title">14. Modifications to the Service</p>
                            <p className="terms_subtitle">We reserve the right in our sole discretion to modify, suspend or discontinue, temporarily or permanently, the Services (or any features or parts thereof) or suspend or discontinue the Auction at any time and without liability therefore.</p>
                        </div>
                        <div className="panel15">
                            <p className="terms_title">15. Dispute Resolution; Arbitration.</p>
                            <p className="terms_subtitle">j. Dispute Resolution. Please read the following arbitration agreement in this Section (“Arbitration Agreement”) carefully. It requires you to arbitrate disputes with Ox Stocks and limits the manner in which you can seek relief from us.
k. Applicability of Arbitration Agreement. You agree that any dispute or claim relating in any way to your access or use of the Service, to any products sold or distributed through the Service, or to any aspect of your relationship with Ox Stocks, will be resolved by binding arbitration, rather than in court, except that (1) you may assert claims in small claims court if your claims qualify; and (2) you or Ox Stocks may seek equitable relief in court for infringement or other misuse of intellectual property rights (such as trademarks, trade dress, domain names, trade secrets, copyrights, and patents).
l. Arbitration Rules and Forum. The Commercial Arbitration Act 2010 (NSW) (“Arbitration Act”) governs the interpretation and enforcement of Arbitration arising under these Terms. To begin an arbitration proceeding, you must send a letter requesting arbitration and describing your claim to legal@oxstocks.com. The arbitration will be conducted by the Australian Disputes Centre (“ADC”), an established alternative dispute resolution provider. Disputes shall be subject to ADC’s most current version of the Arbitration Rules and procedures current at the time of the dispute. You may choose to have the arbitration conducted by telephone, based on written submissions, or in person in the country where you live or at another mutually agreed location. Any judgment on the award rendered by the arbitrator may be entered in any court of competent jurisdiction.
m. Authority of Arbitrator. The arbitrator shall have exclusive authority to (a) determine the scope and enforceability of this Arbitration Agreement and (b) resolve any dispute related to the interpretation, applicability, enforceability or formation of this Arbitration Agreement including, but not limited to any claim that all or any part of this Arbitration Agreement is void or voidable. The arbitration will decide the rights and liabilities, if any, of you and Ox Stocks. The arbitration proceeding will not be consolidated with any other matters or joined with any other cases or parties. The arbitrator shall have the authority to grant motions dispositive of all or part of any claim. The arbitrator shall have the authority to award monetary damages and to grant any non- monetary remedy or relief available to an individual under applicable law, the arbitral forum’s rules, and the Terms (including the Arbitration Agreement). The arbitrator shall issue a written award and statement of decision describing the essential findings and conclusions on which the award is based, including the calculation of any damages awarded. The arbitrator has the same authority to award relief on an individual basis that a judge in a court of law would have. The award of the arbitrator is final and binding upon you and us.
n. Waiver of Right to Litigate. YOU AND OX STOCKS HEREBY WAIVE ANY CONSTITUTIONAL AND STATUTORY RIGHTS TO SUE IN COURT AND LITIGATE BEFORE A JUDICIAL BODY. You and Ox Stocks are instead electing that all claims and disputes shall be resolved by arbitration under this Arbitration Agreement, except as specified in Section 15(b) above. An arbitrator can award on an individual basis the same damages and relief as a court and must follow these Terms as a court would. However, there is no judge or jury in arbitration, and court review of an arbitration award is subject to very limited review.
o. Waiver of Class or Other Non-Individualized Relief. ALL CLAIMS AND DISPUTES WITHIN THE SCOPE OF THIS ARBITRATION AGREEMENT MUST BE ARBITRATED ON AN INDIVIDUAL BASIS AND NOT ON A OR COLLECTIVE CLASS BASIS, ONLY INDIVIDUAL RELIEF IS AVAILABLE, AND CLAIMS OF MORE THAN ONE CUSTOMER OR USER CANNOT BE ARBITRATED OR CONSOLIDATED WITH THOSE OF ANY OTHER CUSTOMER OR USER. If a decision is issued stating that applicable law precludes enforcement of any part of this subsection’s limitations as to a given claim for relief, then that claim must be severed from the arbitration and brought in the state or federal courts located in the State of Delaware. All other claims shall be arbitrated.
p. 30-Day Right to Opt Out. You have the right to opt out of the provisions of this Arbitration Agreement by sending written notice of your decision to opt out to legal@oxstocks.com within 30 days after first becoming subject to this Arbitration Agreement. Your notice must include your name and address, the email address you used to set up your account (if you have one), and an unequivocal statement that you want to opt out of this Arbitration Agreement. If you opt out of this Arbitration Agreement, all other parts of these Terms will continue to apply to you. Opting out of this Arbitration Agreement has no effect on any other arbitration agreements that you may currently have, or may enter in the future, with us.
q. Severability. Except as provided in this Section, if any part or parts of this Arbitration Agreement are found under the law to be invalid or unenforceable, then such specific part or parts shall be of no force and effect and shall be severed and the remainder of the Arbitration Agreement shall continue in full force and effect.
r. Survival of Agreement. This Arbitration Agreement will survive the termination of your relationship with Ox Stocks.
s. Modification. Notwithstanding any provision in these Terms to the contrary, we agree that if Ox Stocks makes any future material change to this Arbitration Agreement, you may reject that change within thirty (30) days of such change becoming effective by writing to legal@oxstocks.com</p>
                        </div>
                        <div className="panel16">
                            <p className="terms_title">16. Governing Law and Venue</p>
                            <p className="terms_subtitle">These Terms, your access to and use of the Service and Content, and your participation in the Auction shall be governed by and construed and enforced in accordance with the laws of England and Wales, without regard to conflict of law rules that would cause the application of the laws of any other jurisdiction that would cause the application of the laws of any other jurisdiction. Any dispute between the parties that is not subject to arbitration or cannot be heard in small claims court, shall be resolved in courts of New South Wales.</p>
                        </div>
                        <div className="panel17">
                            <p className="terms_title">17. Termination</p>
                            <p className="terms_subtitle">Notwithstanding anything contained in these Terms, we reserve the right, without notice and in our sole discretion, to terminate your right to access or use the Service at any time and for any or no reason, and you acknowledge and agree that we shall have no liability or obligation to you in such event and that you will not be entitled to a refund of any amounts that you have already paid to us, to the fullest extent permitted by applicable law. You may cease to use the Website at any time. Refer to our Auction and Marketplace Rules for terms regarding funds or credits held in your account.</p>
                            <p className="terms_subtitle">You may close your Ox Stocks account at any time, subject to:</p>
                            <p className="terms_subtitle">a. not having any outstanding items listed on the Ox Stocks website; and
b. resolving any outstanding matters; and
c. where and if relevant, paying any outstanding fees owing on the account.</p>
                        </div>
                        <div className="panel18">
                            <p className="terms_title">18. Severability</p>
                            <p className="terms_subtitle">If any term, clause or provision of these Terms is held invalid or unenforceable, then that term, clause or provision will be severable from these Terms and will not affect the validity or enforceability of any remaining part of that term, clause or provision, or any other term, clause or provision of these Terms.</p>
                        </div>
                        <div className="panel19">
                            <p className="terms_title">19. Survival</p>
                            <p className="terms_subtitle">The following sections will survive the expiration or termination of these Terms and the termination of your Account: all defined terms and Sections 1-4 and 7-19.</p>
                        </div>
                        <div className="panel20">
                            <p className="terms_title">20. Miscellaneous</p>
                            <p className="terms_subtitle">These Terms along with the Auction and Marketplace Rules constitute the entire agreement between you and Ox Stocks relating to your access to and use of the Services and Content, and your participation in the Auction. These Terms, and any rights and licenses granted hereunder, may not be transferred or assigned by you without the prior written consent of Ox Stocks prior, concurrent or subsequent circumstance, and Ox Stocks’s failure to assert any right or provision under these Terms shall not constitute a waiver of such right or provision. Except as otherwise provided herein, these Terms is intended solely for the benefit of the parties and are not intended to confer third party beneficiary rights upon any other person or entity.</p>
                        </div>
                    </div>
                </div>
            </Fragment>
        )
}

export default Terms;